image: "kallisti5/ci-rust:latest"

before_script:
- rustup toolchain install nightly
- rustup update
- rustup target add i686-unknown-linux-gnu
- rustup target add x86_64-pc-windows-gnu
- rustup target add armv7-unknown-linux-gnueabihf
- echo '[target.x86_64-pc-windows-gnu]' >> ~/.cargo/config
- echo 'linker = "/usr/bin/x86_64-w64-mingw32-gcc"' >> ~/.cargo/config
- echo 'ar = "/usr/bin/x86_64-w64-mingw32-ar"' >> ~/.cargo/config
- echo '[target.armv7-unknown-linux-gnueabihf]' >> ~/.cargo/config
- echo 'linker = "arm-linux-gnueabihf-gcc"' >> ~/.cargo/config

test:cargo:
  script:
  - lscpu
  - rustup -V
  - rustc --version && cargo --version
  - cargo test --jobs 1
  - cargo bench

build:linux-x86_64:
  script:
  - cargo build --release
  artifacts:
    paths:
    - target/

build:linux-i686:
  script:
  - cargo build --release
  artifacts:
    paths:
    - target/

#build:linux-armv7:
#  script:
#  - cargo build --release --target=armv7-unknown-linux-gnueabihf
#  artifacts:
#    paths:
#    - target/
#  allow_failure: true

build:windows-x86_64:
  script:
  - cargo build --release --target=x86_64-pc-windows-gnu
  artifacts:
    paths:
    - target/
  allow_failure: true
