image: "liuchong/rustup:nightly"

before_script:
- apt-get update -yqq
- apt-get install -yqq --no-install-recommends build-essential gcc-mingw-w64-x86-64 gcc-arm-none-eabi gcc-multilib musl musl-dev musl-tools
- rustup toolchain remove nightly
- rustup toolchain install nightly
- rustup update
- rustup target add arm-unknown-linux-gnueabihf
- rustup target add arm-unknown-linux-musleabihf
- rustup target add i686-unknown-linux-gnu
- rustup target add x86_64-unknown-linux-musl

test:cargo:
  script:
  - lscpu
  - rustup -V
  - rustc --version && cargo --version
  - cargo test --jobs 1
  - cargo bench
